# Generated by Django 4.2.5 on 2024-02-28 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p_universities',
            old_name='s_single',
            new_name='info',
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.IntegerField()),
                ('invoices', models.IntegerField()),
                ('accepted', models.IntegerField()),
                ('naccepted', models.IntegerField()),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
                ('langs', models.CharField(max_length=25)),
                ('semesters', models.CharField(max_length=25)),
                ('payment', models.BooleanField(default=False)),
                ('faculties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.faculties')),
                ('univ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.universities')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.IntegerField()),
                ('ielts', models.IntegerField()),
                ('accept', models.IntegerField(choices=[(1, 'Да'), (2, 'Нет')])),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.faculties')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
    ]
