# Generated by Django 4.2.5 on 2024-02-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_s_single_p_universities_info_statistics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnivCab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('found', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('slogan', models.CharField(max_length=100)),
                ('bachelors', models.IntegerField()),
                ('masters', models.IntegerField()),
                ('teachers', models.IntegerField()),
                ('startingsalary', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('gallery', models.FileField(blank=True, null=True, upload_to='')),
                ('map', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
